import { Showcase } from "./showcase"

const demos = [
  {
    id: "1",
    title: "Image Classification",
    description: "Classification: MobileNet, ResNet, EfficientNet Lite",
    imageUrl: "https://microsoft.github.io/webnn-developer-preview/assets/img/demos/ic.jpg",
    demoUrl: "https://microsoft.github.io/webnn-developer-preview/demos/image-classification/",
    codeUrl: "https://github.com/microsoft/webnn-developer-preview/tree/main/demos/image-classification",
    tags: ["GPU", "NPU"],
    framework: ["Transformers.js"],
  },
  {
    id: "2",
    title: "Stable Diffusion 1.5",
    description: "Text-to-Image: Text Encoder, UNet, VAE Decoder, Safety Checker",
    imageUrl: "https://microsoft.github.io/webnn-developer-preview/assets/img/demos/sd1.5.jpg",
    demoUrl: "https://microsoft.github.io/webnn-developer-preview/demos/stable-diffusion-1.5/",
    codeUrl: "https://github.com/microsoft/webnn-developer-preview/tree/main/demos/stable-diffusion-1.5",
    tags: ["GPU"],
    framework: ["ONNX Runtime"],
  },
  {
    id: "3",
    title: "SD Turbo",
    description: "Text-to-Image: Text Encoder, UNet, VAE Decoder, Safety Checker",
    imageUrl: "https://microsoft.github.io/webnn-developer-preview/assets/img/demos/sd-turbo.jpg",
    demoUrl: "https://microsoft.github.io/webnn-developer-preview/demos/sd-turbo/",
    codeUrl: "https://github.com/microsoft/webnn-developer-preview/tree/main/demos/sd-turbo",
    tags: ["GPU", "NPU"],
    framework: ["ONNX Runtime"],
  },
  {
    id: "4",
    title: "Segment Anything",
    description: "Image Segmentation: SAM",
    imageUrl: "https://microsoft.github.io/webnn-developer-preview/assets/img/demos/sam.jpg",
    demoUrl: "https://microsoft.github.io/webnn-developer-preview/demos/segment-anything/",
    codeUrl: "https://github.com/microsoft/webnn-developer-preview/tree/main/demos/segment-anything",
    tags: ["GPU"],
    framework: ["ONNX Runtime"],
  },
  {
    id: "5",
    title: "Whisper Base",
    description: "Automatic Speech Recognition: Whisper Encoder, Decoder",
    imageUrl: "https://microsoft.github.io/webnn-developer-preview/assets/img/demos/whisper.jpg",
    demoUrl: "https://microsoft.github.io/webnn-developer-preview/demos/whisper-base/",
    codeUrl: "https://github.com/microsoft/webnn-developer-preview/tree/main/demos/whisper-base",
    tags: ["GPU", "NPU"],
    framework: ["ONNX Runtime"],
  },
  {
    id: "6",
    title: "Phi-3 Mini",
    description: "Text Generation",
    imageUrl: "https://microsoft.github.io/webnn-developer-preview/assets/img/demos/phi-3-mini.jpg",
    demoUrl: "https://microsoft.github.io/webnn-developer-preview/demos/phi-3-mini/",
    codeUrl: "https://github.com/microsoft/webnn-developer-preview/tree/main/demos/phi-3-mini",
    tags: ["GPU"],
    framework: ["ONNX Runtime"],
  },
  {
    id: "7",
    title: "NNotepad",
    description: "A browser-based playground for experimenting with WebNN",
    imageUrl: "https://webmachinelearning.github.io/assets/images/webnnsamples/nnotepad.png",
    demoUrl: "https://webmachinelearning.github.io/webnn-samples/nnotepad/",
    codeUrl: "https://github.com/webmachinelearning/webnn-samples/tree/master/nnotepad",
    tags: ["CPU", "GPU", "NPU"],
    framework: ["Native WebNN"],
  },
  {
    id: "8",
    title: "Code Editor",
    description: "Evaluate, review and modify WebNN sample codes",
    imageUrl: "https://webmachinelearning.github.io/assets/images/webnnsamples/codeeditor.jpg",
    demoUrl: "https://webmachinelearning.github.io/webnn-samples/code/",
    codeUrl: "https://github.com/webmachinelearning/webnn-samples/tree/master/code",
    tags: ["CPU", "GPU", "NPU"],
    framework: ["Native WebNN"],
  },
  {
    id: "9",
    title: "Image Classification",
    description: "Classification: MobileNet, SqueezeNet, ResNet, EfficientNet Lite",
    imageUrl: "https://webmachinelearning.github.io/assets/images/webnnsamples/ic.jpg",
    demoUrl: "https://webmachinelearning.github.io/webnn-samples/image_classification/",
    codeUrl: "https://github.com/webmachinelearning/webnn-samples/tree/master/image_classification",
    tags: ["CPU", "GPU", "NPU"],
    framework: ["Native WebNN"],
  },
  {
    id: "10",
    title: "Handwritten Classification",
    description: "Use LeNet to classify handwritten digits from the MNIST data set",
    imageUrl: "https://webmachinelearning.github.io/assets/images/webnnsamples/handwritten.png",
    demoUrl: "https://webmachinelearning.github.io/webnn-samples/lenet/",
    codeUrl: "https://github.com/webmachinelearning/webnn-samples/tree/master/lenet",
    tags: ["CPU", "GPU"],
    framework: ["Native WebNN"],
  },
  {
    id: "11",
    title: "Fast Style Transfer",
    description: "Applying the STARRY NIGHT and other styles of Van Gogh to image",
    imageUrl: "https://webmachinelearning.github.io/assets/images/webnnsamples/starrynight.jpg",
    demoUrl: "https://webmachinelearning.github.io/webnn-samples/style_transfer/",
    codeUrl: "https://github.com/webmachinelearning/webnn-samples/tree/master/style_transfer",
    tags: ["CPU", "GPU"],
    framework: ["Native WebNN"],
  },  {
    id: "12",
    title: "Object Detection",
    description: "Detecting instances of semantic objects in digital images and videos",
    imageUrl: "https://webmachinelearning.github.io/webnn-samples/common/img/od.png",
    demoUrl: "https://webmachinelearning.github.io/webnn-samples/object_detection/",
    codeUrl: "https://github.com/webmachinelearning/webnn-samples/tree/master/object_detection/",
    tags: ["CPU", "GPU", "NPU"],
    framework: ["Native WebNN"],
  },
  {
    id: "13",
    title: "Noise Suppression",
    description: "A NSNet2 baseline impl. of deep learning-based noise suppression",
    imageUrl: "https://webmachinelearning.github.io/webnn-samples/common/img/noise.png",
    demoUrl: "https://webmachinelearning.github.io/webnn-samples/nsnet2/",
    codeUrl: "https://github.com/webmachinelearning/webnn-samples/tree/master/nsnet2/",
    tags: ["CPU", "GPU"],
    framework: ["Native WebNN"],
  },  {
    id: "14",
    title: "Noise Suppression",
    description: "An RNNoise baseline impl. of deep learning-based noise suppression",
    imageUrl: "https://webmachinelearning.github.io/webnn-samples/common/img/rnnoise.png",
    demoUrl: "https://webmachinelearning.github.io/webnn-samples/rnnoise/",
    codeUrl: "https://github.com/webmachinelearning/webnn-samples/tree/master/rnnoise/",
    tags: ["CPU", "GPU"],
    framework: ["Native WebNN"],
  },
  {
    id: "15",
    title: "Semantic Segmentation",
    description: "Partitioning image into semantically meaningful parts",
    imageUrl: "https://webmachinelearning.github.io/webnn-samples/common/img/ss.png",
    demoUrl: "https://webmachinelearning.github.io/webnn-samples/semantic_segmentation/",
    codeUrl: "https://github.com/webmachinelearning/webnn-samples/tree/master/semantic_segmentation/",
    tags: ["CPU", "GPU"],
    framework: ["Native WebNN"],
  },  {
    id: "16",
    title: "Facial Landmark Detection",
    description: "Detecting facial landmarks like eyes, nose, mouth, etc.",
    imageUrl: "https://webmachinelearning.github.io/webnn-samples/common/img/fld.png",
    demoUrl: "https://webmachinelearning.github.io/webnn-samples/facial_landmark_detection/",
    codeUrl: "https://github.com/webmachinelearning/webnn-samples/tree/master/facial_landmark_detection/",
    tags: ["CPU", "GPU"],
    framework: ["Native WebNN"],
  },
  {
    id: "17",
    title: "Face Recognition",
    description: "Detecting faces of participants using object detection",
    imageUrl: "https://webmachinelearning.github.io/webnn-samples/common/img/fr.png",
    demoUrl: "https://webmachinelearning.github.io/webnn-samples/face_recognition/",
    codeUrl: "https://github.com/webmachinelearning/webnn-samples/tree/master/face_recognition/",
    tags: ["CPU", "GPU"],
    framework: ["Native WebNN"],
  },
]

export function Showcases() {
  return (
    <div className="min-h-screen">
      <h1 className="text-4xl font-title font-bold text-center pt-12">Showcase</h1>
      <Showcase demos={demos} />
    </div>
  )
}

